apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote-rs

spec:
  minReadySeconds: 0
  replicas: 2
  selector:
    matchLabels:
      app: python
      role: vote
      version: v1
    matchExpressions:
      - key: version
        operator: Exists

  template:
    metadata:
      name: vote
      labels: 
        app: python
        role: vote
        version: v1
    spec:
      containers:
      - name: app
        image: schoolofdevops/vote:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"